### ISSUE TITLE
Incorporate experimental route snapper improvements

### ISSUE THREAD

**Issue by dabreegster** [nptscot/npw#27]
I have an in-progress rewrite to the route snapper UI. It uses maplibre markers for dragging things around, which dramatically improves the hit detection. And a hopefully much more clear on-map control panel, with more explicit modes.
 
https://acteng.github.io/atip/route_snapper_next_gen/scheme.html?authority=TA_Telford+and+Wrekin&schema=v1&style=streets#10.45/52.721/-2.4898

![image](https://github.com/user-attachments/assets/a6f7dbfd-3770-4186-8bff-b2bf7e79e991)

**Comment by dabreegster** [comment]
The changes are now live / visible in https://acteng.github.io/atip/files.html?authority=TA_South%20Yorkshire%20Combined%20Authority&schema=v2, the route tool. Likely going to port them over here soon.

**Comment by Robinlovelace** [comment]
I just gave the new route UI a try in the ATIP test site and really liked it. Big :+1: to benefiting from these improvements in the NPW. Screenshot showing level of detail that the 'middle points' mode allows:

![image](https://github.com/user-attachments/assets/e043749c-f88d-4257-b1aa-ab3aa115fec9)
