### ISSUE TITLE
Feedback / open questions for 30 October

### ISSUE THREAD

**Issue by dabreegster** [nptscot/npw#31]
Try out latest at https://nptscot.github.io/npw/

I'll write down open questions before the meeting here, then fill out issues after

# Coverage metrics

"% of schools/GPs/etc within 100m buffer of edited network"

- 100m network buffer from the edited network only?
- What about the existing network?
- Exclude mixed traffic streets?
- What's "close enough" to the network -- only high LoS streets in between the network and destination?
  - From the network, flood as far as possible until hitting severances? What's their definition?
- Snapping the destination to the network -- easy for points (schools), unclear for large polygons (town centres)

# High NPT route coverage

- The described approach in slides
  - Decide a quantile per study area, or some other cutoff?
  - What does "% of high value routes covered" mean -- count by road segments? Length?
  - Same as above, mixed traffic streets? Existing network?
- The alt implemented now (ignores the pregenerated rnet!)
  - Just sum total demand on and off the network?
  - Be clear about limits of how many OD pairs processed

# Directness

- Review how it's done so far
  - Weighted sample using the OD data?
- Need to decide what route cost function is used for this (and also the above)
  - fast or quiet?
  - need to start a cost function actually using this

# Editing mechanics

- Routes that cross edited bits
- Maybe handle using the auto-split, likely needed anyway for recommended infra type
- What's important metadata to preserve about a "route" -- name, description?

# UI styling

- Revisit govuk, matching existing NPT, etc

**Comment by mvl22** [comment]
> Revisit govuk, matching existing NPT, etc

Decision today to use the [SG Design system](https://designsystem.gov.scot/).

I propose I submit a PR implementing this so you can focus on the more deep technical stuff, once I've looked into it properly.
