### ISSUE TITLE
UX: new browser tab opens when you are drawing a route if you click on existing infrastructure

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npw#33]
As illustrated in the video session below.

https://github.com/user-attachments/assets/ff2a447f-2202-4d2e-bd63-c051a3b17845

- [ ] Change the 'click on link' functionality when in editor mode so you don't see popups and certainly don't get taken to a new page in case you want to click somewhere where there is already infrastructure.

- [ ] Ideas on a fix: make clicking on a link generate a popup: this is worth doing anyway and makes the UX less surprsing, and more consistent with NPT where clicking on a link shows info in a popup and the options to see more on Google Streetview or OSM (that is probably a separate issue but putting here as related, can create new issue from that)

**Comment by Robinlovelace** [comment]
Thanks @dabreegster. I just tried to verify the fix and look to provide additional input, but seems the site is down:

![image](https://github.com/user-attachments/assets/ab42d3e0-2339-4439-b562-f9e6612fb501)

Source: https://nptscot.github.io/npw/#10.74/55.9127/-3.2733

Error message:

```
Failed to load 'http://localhost:5173/offline/light_style.json'. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with 'TypeError: NetworkError when attempting to fetch resource.'.
```

Just wanted to check: am I missing something basic? Before opening a separate issue

**Comment by dabreegster** [comment]
Known issue. I've made some breaking changes to the binary format and need to regenerate all areas, but I won't have access to fast internet/computer for a few days. I'll get a few areas working again. As we get closer to a first deliverable, I'll stop breaking the dev demo, or we could start deploying to a real production environment.

**Comment by Robinlovelace** [comment]
Sounds good and no big rush.

**Comment by dabreegster** [comment]
https://nptscot.github.io/npw/ is working again, Edinburgh only. If you get an error when loading, you have to clear local storage or open from incognito browser
