### ISSUE TITLE
Updated boundaries file

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npw#39]
Hey @dabreegster I've just generated a new boundaries file: https://github.com/nptscot/npt/releases/download/boundaries-2024/la_regions_scotland_bfe_simplified_2023.geojson

Not that much different but less liable to cut seaside roads, as per https://github.com/nptscot/npt/issues/555

**Comment by dabreegster** [comment]
Thanks! Updated here, but I probably won't regenerate all the NPW files till later this weekend.
