### ISSUE TITLE
Routes that cross existing routes not possible but should be?

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npw#43]
As shown below I tried creating a new route to help generate a joined-up network but was not allowed:

![image](https://github.com/user-attachments/assets/0be6aa36-8bd6-4cc9-90b0-eb0086db8719)

Clicking "Finish" after the app was in that state led to the following message:

![image](https://github.com/user-attachments/assets/5296b12e-392a-4e31-a7a4-29cb7c036b7b)

Some overlaps and certainly crossings should be possible if not encouraged given the importance of joined-up-ness.

**Comment by dabreegster** [comment]
This was a temporary limitation. The new flow we discussed was:

1) The user draws a possibly long route
2) The tool uses the CbD guidelines to auto-assign the most appropriate infrastructure type to each road segment
3) The tool splits the long route into sections, based on these auto-assigned infrastructure types and any overlaps with other sections

Currently the user can specify a name, tier, and free-form notes per route. When there's overlap with something else, should we completely ignore it, or append notes, or warn when the tier differs, or overwrite everything?

I'm also having some difficulty coming up with the automatic infra recommendation based on 
![image](https://github.com/user-attachments/assets/4afc3740-c27a-466f-a7f7-8894d6952ba2)
In the call, we said we pretty much always want segregated wide or off-road, except when leaving mixed traffic is fine. As a first cut, I'm thinking about leaving high LoS roads alone (mixed traffic) and making all others segregated wide. I need to first detect situations that're off-road properly, to be able to distinguish those cases.

**Comment by Robinlovelace** [comment]
> I'm thinking about leaving high LoS roads alone (mixed traffic) and making all others segregated wide. 

Sounds good to me :+1: 

In my experience with `osmactive` the devil is in the details and the best feedback I got was after initial implementations and showing to people with local knowledge. Segregated (wide) by default unless already high LoS (which will be the case for off road routes and low traffic mixed traffic) is a good starting point. In cases where there's a clash between 2 different recommendations for the same segments, how about we go with the most separated on the hierarchy?

**Comment by dabreegster** [comment]
The flow around auto-splitting needs more work, but this particular issue is now fixed -- when you overlap an existing route, that section is just left unmodified

**Comment by Robinlovelace** [comment]
Amazing, thanks Dustin, look forward to testing it!
