### ISSUE TITLE
Split-out `match_lines` as standalone crate

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npw#45]
For use elsewhere, I'm well up for having a bash at this. Reason: we're having some issues with the [R implementation](https://docs.ropensci.org/stplanr/reference/rnet_merge.html) and, at present, struggling to get the `rnetmatch` implementation packaged and available for use: https://github.com/nptscot/rnetmatch/issues/42

I saw this and thought this could be a great thing to do, I'm up for giving it a go:

https://github.com/nptscot/npw/blob/5fc92c2fb21404b1029bc48c44308df443cdb796/cli/src/match_lines.rs#L8

**Comment by Robinlovelace** [comment]
Any pointers welcome @dabreegster, I guess starting with some inputs and expected outputs for tests, and putting the code in a standalone repo. Can do both I think... but pointers appreciated.

**Comment by dabreegster** [comment]
https://github.com/nptscot/match_linestrings
Got a CLI started. Please feel free to add some interesting test cases. I have limited time to help further right now, but I'll try to keep you unblocked.
